name = "agrovisao-site"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./dist"

# D1 database
# Crie com: npx wrangler d1 create agro-visao
# Execute migrations com: npx wrangler d1 migrations apply agro-visao
[[d1_databases]]
binding = "DB"
database_name = "agro-visao"
database_id = "6449e722-9464-4df2-b09d-6fe76baeaca0"
